name: CI

on: [push, pull_request]

env:
  TEXLIVE_VERSION: 2022
  TERM: xterm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup
        run: |
          # install current version of inkscape
          sudo add-apt-repository -y ppa:inkscape.dev/stable
          sudo apt-get update -q
          # curl for download, dbus-x11 fixes a lot of warnings from inkscape that
          # cluttered the log
          sudo apt-get install inkscape curl dbus-x11 lcdf-typetools -y
          inkscape --version

          # install texlive
          pip install https://github.com/MaxNoe/texlive-batch-installation/archive/master.tar.gz
          install_texlive -t $TEXLIVE_VERSION --collection='-a' --package-file tex-packages.txt -p $HOME/.local/texlive -v
          echo "$HOME/.local/texlive/$TEXLIVE_VERSION/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Install Montserrat Font
        run: |
          curl -Lo $HOME/montserrat.zip https://fonts.google.com/download?family=Montserrat
          mkdir -p $HOME/.local/share/fonts
          unzip -d $HOME/.local/share/fonts $HOME/montserrat.zip
          fc-cache

          echo "fc-list Montserrat"
          fc-list 'Montserrat'

          luaotfload-tool --update --force

          echo "luaotfload --find='Montserrat'"
          luaotfload-tool --find='Montserrat'

          echo "otfinfo -a $HOME/.local/share/fonts/static/Montserrat-Regular.ttf"
          otfinfo -a $HOME/.local/share/fonts/static/Montserrat-Regular.ttf

      - name: Build
        run: |
          which lualatex
          lualatex test.tex
